"use client";

import { useEffect, useState } from "react";

const money = (value: string | number, currency?: string) => `${Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 })}${currency ? ` ${currency}` : ""}`;

export default function RemittanceDetailClient({ id }: { id: string }) {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    fetch("/api/premium", { cache: "no-store" })
      .then(async (response) => {
        const json = await response.json();
        if (!response.ok) throw new Error(json.error || "Transaction ဖွင့်မရပါ");
        return json;
      })
      .then(setData)
      .catch((reason) => setError(reason instanceof Error ? reason.message : "Transaction ဖွင့်မရပါ"));
  }, []);

  if (error) return <div className="card text-red-600">{error}</div>;
  if (!data) return <div className="card">Transaction ဖွင့်နေပါသည်...</div>;
  const tx = data.remittances.find((row: any) => row.id === id);
  if (!tx) return <div className="card">Transaction မတွေ့ပါ။</div>;
  const wallet = (walletId: string) => data.wallets.find((item: any) => item.id === walletId);
  const source = wallet(tx.sourceWalletId);
  const target = wallet(tx.targetWalletId);

  return (
    <div className="mx-auto max-w-2xl">
      <div className="mb-4 flex justify-end print:hidden"><button onClick={() => window.print()} className="btn-primary px-5 py-3">Print / PDF</button></div>
      <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm print:border-0 print:shadow-none">
        <div className="border-b border-slate-200 pb-5 text-center">
          <h1 className="text-3xl font-black text-blue-700">Wallet Note</h1>
          <p className="mt-1 text-sm text-slate-500">Transaction Receipt</p>
        </div>
        <div className="my-5 grid gap-3 text-sm">
          <Line label="Transaction ID" value={tx.id} />
          <Line label="နေ့စွဲ" value={tx.date} />
          <Line label="ဖောက်သည်" value={tx.customerName} />
          <Line label="လုပ်ဆောင်ချက်" value={tx.action === "mmk-thb" ? "ကျပ်ပေး ဘတ်ယူ" : "ဘတ်ပေး ကျပ်ယူ"} />
          <Line label="ထွက် Wallet" value={`${source?.name || "-"} (${source?.currency || ""})`} />
          <Line label="ဝင် Wallet" value={`${target?.name || "-"} (${target?.currency || ""})`} />
          <Line label="ထွက်ငွေ" value={money(tx.sourceAmount, source?.currency)} />
          <Line label="Rate" value={money(tx.rate)} />
          <Line label="ဝင်ငွေ" value={money(tx.targetAmount, target?.currency)} />
          <Line label="Fee" value={money(tx.feeAmount, target?.currency)} />
          <Line label="Total" value={money(tx.totalAmount, target?.currency)} strong />
          <Line label="နည်းလမ်း" value={tx.transferMethod} />
          <Line label="Status" value={tx.statusDetail || "-"} />
          <Line label="မှတ်ချက်" value={tx.note || "-"} />
        </div>
        <p className="border-t border-slate-200 pt-4 text-center text-xs text-slate-400">Generated by Wallet Note</p>
      </article>
    </div>
  );
}

function Line({ label, value, strong }: { label: string; value: any; strong?: boolean }) {
  return <div className="flex justify-between gap-4 rounded-xl bg-slate-50 px-4 py-3"><span className="text-slate-500">{label}</span><span className={`text-right ${strong ? "text-lg font-black" : "font-bold"}`}>{value}</span></div>;
}
