import bcrypt from "bcryptjs";
import crypto from "node:crypto";
import {SYSTEM_SHEET_ID,appendObject,readTable} from "./sheets-client.js";
import {USER_TABS,ensureTabs,updateFields} from "./schema.js";
import {auth,clearSession,currentUser,getUsers,invalidateUsers,setSession} from "./auth.js";

function sheetId(input){const v=String(input||"").trim(),m=v.match(/\/spreadsheets\/d\/([a-zA-Z0-9_-]+)/),id=m?.[1]||v;if(!/^[a-zA-Z0-9_-]{20,}$/.test(id))throw new Error("Invalid Google Sheet URL or ID");return id}

export function accountRoutes(app){
  app.post("/api/register",async(req,res,next)=>{try{const name=String(req.body?.name||"").trim(),email=String(req.body?.email||"").trim().toLowerCase(),username=String(req.body?.username||"").trim().toLowerCase(),password=String(req.body?.password||"");if(name.length<2||!/^\S+@\S+\.\S+$/.test(email)||!/^[a-zA-Z0-9_.-]{3,30}$/.test(username)||password.length<8)return res.status(400).json({error:"Registration information is invalid"});const list=await getUsers(true);if(list.some(u=>String(u.email).toLowerCase()===email))return res.status(409).json({error:"Email is already registered"});if(list.some(u=>String(u.username).toLowerCase()===username))return res.status(409).json({error:"Username is already taken"});const id=crypto.randomUUID();await appendObject(SYSTEM_SHEET_ID,"Users",{id,name,email,username,passwordHash:await bcrypt.hash(password,10),role:"user",status:"Active",spreadsheetId:"",sheetConnectedAt:"",createdAt:new Date().toISOString()});invalidateUsers();setSession(res,id);res.json({ok:true})}catch(e){next(e)}});
  app.post("/api/login",async(req,res,next)=>{try{const identity=String(req.body?.identity||"").trim().toLowerCase(),password=String(req.body?.password||"");const user=(await getUsers(true)).find(u=>String(u.email).toLowerCase()===identity||String(u.username).toLowerCase()===identity);if(!user||!(await bcrypt.compare(password,user.passwordHash||"")))return res.status(401).json({error:"Incorrect email, username or password"});if(user.status!=="Active")return res.status(403).json({error:"This account is suspended"});setSession(res,user.id);res.json({ok:true,connected:Boolean(user.spreadsheetId?.trim())})}catch(e){next(e)}});
  app.post("/api/logout",(req,res)=>{clearSession(res);res.json({ok:true})});
  app.get("/api/session",async(req,res,next)=>{try{const user=await currentUser(req);if(!user)return res.json({authenticated:false});res.json({authenticated:true,user:{id:user.id,name:user.name,email:user.email,username:user.username,role:user.role},connected:Boolean(user.spreadsheetId?.trim()),spreadsheetUrl:user.spreadsheetId?`https://docs.google.com/spreadsheets/d/${user.spreadsheetId}/edit`:""})}catch(e){next(e)}});
  app.get("/api/sheet-connection",auth,(req,res)=>{const id=req.user.spreadsheetId?.trim()||"";res.json({connected:Boolean(id),spreadsheetId:id,spreadsheetUrl:id?`https://docs.google.com/spreadsheets/d/${id}/edit`:"",connectedAt:req.user.sheetConnectedAt||"",serviceAccountEmail:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL||""})});
  app.post("/api/sheet-connection",auth,async(req,res)=>{try{const id=sheetId(req.body?.sheet),title=await ensureTabs(id,USER_TABS),settings=await readTable(id,"Settings");if(!settings.rows.length){await appendObject(id,"Settings",{key:"THB_TO_MMK",value:0});await appendObject(id,"Settings",{key:"LOTTERY_PAYOUT_MULTIPLIER",value:500})}await updateFields(SYSTEM_SHEET_ID,"Users",req.user.id,{spreadsheetId:id,sheetConnectedAt:new Date().toISOString()});invalidateUsers();res.json({ok:true,title,spreadsheetId:id})}catch(e){res.status(400).json({error:e.message||"Unable to connect Google Sheet"})}});
  app.delete("/api/sheet-connection",auth,async(req,res,next)=>{try{await updateFields(SYSTEM_SHEET_ID,"Users",req.user.id,{spreadsheetId:"",sheetConnectedAt:""});invalidateUsers();res.json({ok:true})}catch(e){next(e)}});
}
